# Generated by Django 4.0.3 on 2022-03-11 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_category_snippet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
