# Generated by Django 4.0.3 on 2022-03-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='code',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
