# Generated by Django 4.0.3 on 2022-03-14 01:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_snippet_code_alter_snippet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
