# Generated by Django 4.0.3 on 2022-03-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_alter_snippet_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
