# Generated by Django 4.0.3 on 2022-03-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='CustomUser',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fav_snips',
        ),
    ]
