# Generated by Django 4.0.3 on 2022-03-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_alter_snippet_code'),
        ('snippets', '0009_alter_profile_avatar'),
    ]

    operations = [
    ]
