# Generated by Django 4.0.3 on 2022-03-16 23:56
# Generated by Django 4.0.3 on 2022-03-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0010_merge_20220316_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/'),
        ),
    ]
