# Generated by Django 4.0.3 on 2022-03-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0011_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='copy_count',
            field=models.IntegerField(default=0),
        ),
    ]
