# Generated by Django 4.0.3 on 2022-03-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0011_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(blank=True, choices=[('Py', 'Python'), ('JS', 'JavaScript'), ('HT', 'HTML'), ('CS', 'CSS'), ('DJ', 'Django')], default=None, max_length=20, null=True),
        ),
    ]
