# Generated by Django 4.0.3 on 2022-03-17 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0014_alter_snippet_language'),
        ('snippets', '0015_alter_snippet_description'),
    ]

    operations = [
    ]
